// Add these additional strings to your AppLocalizations class

// Additional English strings to add to _englishStrings map:
const Map<String, String> _additionalEnglishStrings = {
  // Form validation
  'email_required': 'Email is required',
  'invalid_email': 'Please enter a valid email',
  'password_required': 'Password is required',
  'password_min_length': 'Password must be at least 6 characters',
  
  // General actions
  'change_language': 'Change Language',
  'updated_successfully': 'updated successfully',
  'changed_successfully': 'changed successfully',
  'successful': 'successful',
  
  // Settings
  'notifications': 'Notifications',
  'privacy_security': 'Privacy & Security',
  'app_info': 'App Information',
  'developed_with_flutter': 'Developed with Flutter',
  
  // Common phrases
  'current_language': 'Current Language',
  'select_language': 'Select Language',
  'version': 'Version',
  'about': 'About',
  'help': 'Help',
  'support': 'Support',
  'feedback': 'Feedback',
  'rate_app': 'Rate App',
  'share_app': 'Share App',
  'terms_conditions': 'Terms & Conditions',
  'privacy_policy': 'Privacy Policy',
};

// Additional Spanish strings to add to _spanishStrings map:
 const Map<String, String> _additionalSpanishStrings = {
  'email_required': 'El correo electrónico es obligatorio',
  'invalid_email': 'Por favor ingresa un correo válido',
  'password_required': 'La contraseña es obligatoria',
  'password_min_length': 'La contraseña debe tener al menos 6 caracteres',
  'change_language': 'Cambiar Idioma',
  'updated_successfully': 'actualizado exitosamente',
  'changed_successfully': 'cambiado exitosamente',
  'successful': 'exitoso',
  'notifications': 'Notificaciones',
  'privacy_security': 'Privacidad y Seguridad',
  'app_info': 'Información de la App',
  'developed_with_flutter': 'Desarrollado con Flutter',
  'current_language': 'Idioma Actual',
  'select_language': 'Seleccionar Idioma',
  'version': 'Versión',
  'about': 'Acerca de',
  'help': 'Ayuda',
  'support': 'Soporte',
  'feedback': 'Comentarios',
  'rate_app': 'Calificar App',
  'share_app': 'Compartir App',
  'terms_conditions': 'Términos y Condiciones',
  'privacy_policy': 'Política de Privacidad',
};

// Additional French strings to add to _frenchStrings map:
 const Map<String, String> _additionalFrenchStrings = {
  'email_required': 'L\'email est requis',
  'invalid_email': 'Veuillez entrer un email valide',
  'password_required': 'Le mot de passe est requis',
  'password_min_length': 'Le mot de passe doit contenir au moins 6 caractères',
  'change_language': 'Changer de Langue',
  'updated_successfully': 'mis à jour avec succès',
  'changed_successfully': 'changé avec succès',
  'successful': 'réussi',
  'notifications': 'Notifications',
  'privacy_security': 'Confidentialité et Sécurité',
  'app_info': 'Informations sur l\'App',
  'developed_with_flutter': 'Développé avec Flutter',
  'current_language': 'Langue Actuelle',
  'select_language': 'Sélectionner la Langue',
  'version': 'Version',
  'about': 'À Propos',
  'help': 'Aide',
  'support': 'Support',
  'feedback': 'Commentaires',
  'rate_app': 'Évaluer l\'App',
  'share_app': 'Partager l\'App',
  'terms_conditions': 'Termes et Conditions',
  'privacy_policy': 'Politique de Confidentialité',
};

// Additional German strings to add to _germanStrings map:
 const Map<String, String> _additionalGermanStrings = {
  'email_required': 'E-Mail ist erforderlich',
  'invalid_email': 'Bitte geben Sie eine gültige E-Mail ein',
  'password_required': 'Passwort ist erforderlich',
  'password_min_length': 'Passwort muss mindestens 6 Zeichen haben',
  'change_language': 'Sprache Ändern',
  'updated_successfully': 'erfolgreich aktualisiert',
  'changed_successfully': 'erfolgreich geändert',
  'successful': 'erfolgreich',
  'notifications': 'Benachrichtigungen',
  'privacy_security': 'Datenschutz & Sicherheit',
  'app_info': 'App-Informationen',
  'developed_with_flutter': 'Entwickelt mit Flutter',
  'current_language': 'Aktuelle Sprache',
  'select_language': 'Sprache Auswählen',
  'version': 'Version',
  'about': 'Über',
  'help': 'Hilfe',
  'support': 'Support',
  'feedback': 'Feedback',
  'rate_app': 'App Bewerten',
  'share_app': 'App Teilen',
  'terms_conditions': 'Geschäftsbedingungen',
  'privacy_policy': 'Datenschutzrichtlinie',
};

// Additional Hindi strings to add to _hindiStrings map:
 const Map<String, String> _additionalHindiStrings = {
  'email_required': 'ईमेल आवश्यक है',
  'invalid_email': 'कृपया एक वैध ईमेल दर्ज करें',
  'password_required': 'पासवर्ड आवश्यक है',
  'password_min_length': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
  'change_language': 'भाषा बदलें',
  'updated_successfully': 'सफलतापूर्वक अपडेट किया गया',
  'changed_successfully': 'सफलतापूर्वक बदला गया',
  'successful': 'सफल',
  'notifications': 'सूचनाएं',
  'privacy_security': 'गोपनीयता और सुरक्षा',
  'app_info': 'ऐप जानकारी',
  'developed_with_flutter': 'Flutter के साथ विकसित',
  'current_language': 'वर्तमान भाषा',
  'select_language': 'भाषा चुनें',
  'version': 'संस्करण',
  'about': 'के बारे में',
  'help': 'मदद',
  'support': 'सहायता',
  'feedback': 'प्रतिक्रिया',
  'rate_app': 'ऐप रेटिंग दें',
  'share_app': 'ऐप साझा करें',
  'terms_conditions': 'नियम और शर्तें',
  'privacy_policy': 'गोपनीयता नीति',
};

// Additional Arabic strings to add to _arabicStrings map:
 const Map<String, String> _additionalArabicStrings = {
  'email_required': 'البريد الإلكتروني مطلوب',
  'invalid_email': 'يرجى إدخال بريد إلكتروني صحيح',
  'password_required': 'كلمة المرور مطلوبة',
  'password_min_length': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
  'change_language': 'تغيير اللغة',
  'updated_successfully': 'تم التحديث بنجاح',
  'changed_successfully': 'تم التغيير بنجاح',
  'successful': 'ناجح',
  'notifications': 'الإشعارات',
  'privacy_security': 'الخصوصية والأمان',
  'app_info': 'معلومات التطبيق',
  'developed_with_flutter': 'تم التطوير باستخدام Flutter',
  'current_language': 'اللغة الحالية',
  'select_language': 'اختر اللغة',
  'version': 'الإصدار',
  'about': 'حول',
  'help': 'مساعدة',
  'support': 'الدعم',
  'feedback': 'ملاحظات',
  'rate_app': 'قيم التطبيق',
  'share_app': 'شارك التطبيق',
  'terms_conditions': 'الشروط والأحكام',
  'privacy_policy': 'سياسة الخصوصية',
};